version: '3.8'

services:
  accountsdb:
    image: postgres:9.6.10
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ../sql/Accounts.sql/:/docker-entrypoint-initdb.d/Accounts.sql
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: rootadmin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: ACCOUNTS


  transactionsdb:
    image: library/postgres:10.5
    restart: always
    ports:
      - "5431:5432"
    volumes:
      - ../sql/Transactions.sql:/docker-entrypoint-initdb.d/Transactions.sql
    environment:
      POSTGRES_USER: rootadmin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: TRANSACTIONS

  credit-application-db:
    image: library/postgres:10.5
    restart: always
    ports:
      - "5429:5432"
    volumes:
      - ../sql/creditApplication.sql:/docker-entrypoint-initdb.d/creditApplication.sql
    environment:
      POSTGRES_USER: rootadmin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: CREDITAPPLICATION


  db2:
    build: ./loans
    image: db2_loans
    hostname: db2
    privileged: true
    environment:
      LICENSE: accept
      DB2INST1_PASSWORD: db2pwd
      DBNAME: Loans
    ports:
      - "50000:50000"
    volumes:
      - ./data/loans:/database


volumes:
  pg-dataset:


