version: '3.8'

services:

  accountsdb:
    image: postgres:9.6.10
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ../sql/Accounts.sql/:/docker-entrypoint-initdb.d/Accounts.sql
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: rootadmin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: ACCOUNTS

  transactionsdb:
    image: library/postgres:10.5
    restart: always
    ports:
      - "5431:5432"
    volumes:
      - ../sql/Transactions.sql:/docker-entrypoint-initdb.d/Transactions.sql
    environment:
      POSTGRES_USER: rootadmin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: TRANSACTIONS

  credit-application-db:
    image: library/postgres:10.5
    restart: always
    ports:
      - "5429:5432"
    volumes:
      - ../sql/creditApplication.sql:/docker-entrypoint-initdb.d/creditApplication.sql
    environment:
      POSTGRES_USER: rootadmin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: CREDITAPPLICATION

  accounts-service:
    image: core-banking/accounts-service
    ports:
      - "8080:8080"
    depends_on:
      - accountsdb
    environment:
    - "SPRING_PROFILES_ACTIVE=test"

  transactions-service:
    image: core-banking/transactions-service
    ports:
      - "8090:8090"
    depends_on:
      - transactionsdb
    environment:
      - "SPRING_PROFILES_ACTIVE=test"

  data-service:
    image: core-banking/data-service
    ports:
      - "4000:4000"
    depends_on:
      - transactions-service
      - accounts-service
    environment:
      ACCOUNTS_HOST: 'http://accounts-service:8080'
      TRANSACTIONS_HOST: 'http://transactions-service:8090'
      PORT: 4000

  frontend:
    image: core-banking/frontend
    ports:
      - "8100:80"
    depends_on:
      - transactions-service
      - accounts-service
      - data-service

  credit-application-service:
    image: core-banking/credit-application-service
    ports:
      - "8070:8070"
    depends_on:
      - transactions-service
      - accounts-service
      - data-service
    environment:
      - "SPRING_PROFILES_ACTIVE=test"

volumes:
  pg-dataset:
