version: '3.8'

services:

  accountsdb:
    image: postgres:9.6.10
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ../sql/Accounts.sql/:/docker-entrypoint-initdb.d/Accounts.sql
    environment:
      DATABASE_HOST: 127.0.0.1
      POSTGRES_USER: rootadmin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: ACCOUNTS


  transactionsdb:
    image: library/postgres:10.5
    restart: always
    ports:
      - "5431:5432"
    volumes:
      - ../sql/Transactions.sql:/docker-entrypoint-initdb.d/Transactions.sql
    environment:
      POSTGRES_USER: rootadmin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: TRANSACTIONS

  credit-application-db:
    image: library/postgres:10.5
    restart: always
    ports:
      - "5429:5432"
    volumes:
      - ../sql/creditApplication.sql:/docker-entrypoint-initdb.d/creditApplication.sql
    environment:
      POSTGRES_USER: rootadmin
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: CREDITRISK


volumes:
  pg-dataset:
