# DEV profile
# - in-memory H2 database
spring:
  datasource:
    database-platform: org.hibernate.dialect.H2Dialect
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      enabled: true
      path: /h2-console
