# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Accounts service CI pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Run tests and Publish package
        uses: xlui/action-maven-cli@master
        with:
          lifecycle: 'mvn -B clean deploy --file data-access-services/accounts-service/pom.xml -am'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
