# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Accounts service CI pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout code
        uses: actions/checkout@v2

      - name: 2. Run maven test
        uses: xlui/action-maven-cli@master
        with:
          lifecycle: 'mvn -B clean deploy --file data-access-services/accounts-service/pom.xml -am'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
